### ISSUE TITLE
Write tests for sessions.

### ISSUE THREAD

**Issue by stephenhuh** [afreymiller/talhelm-project#56]

**Comment by afreymiller** [comment]
1. User gets redirected to /users landing view (which does not have login/signup forms) when they hit /users after logging in or signing up.
2. User gets directed to /users landing view (which contains login/signup forms) when they hit /users after logging out and re-entering /users.
3. Sessions last duration specified in sessionStore property (test with 30 seconds)
4. Re-activated sessions last duration specified in sessionStore property (test with 20 seconds on re-activate, 30 seconds initially)
